name: Convert Markdown to JSON

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - 'Azure roles/README.md'
      - 'Entra roles/README.md'
      - 'Microsoft Graph application permissions/README.md'

permissions:
  contents: write
  id-token: write

jobs:
  convert_markdown_to_json:
    runs-on: ubuntu-latest
    steps:
    - name: Az Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302   # v2.2.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Get ARM access token
      id: get-arm-token
      run: echo "token=$(az account get-access-token --resource=https://management.azure.com --query accessToken -o tsv)" >> $GITHUB_OUTPUT

    - name: Get MS Graph access token
      id: get-msgraph-token
      run: echo "token=$(az account get-access-token --resource=https://graph.microsoft.com --query accessToken -o tsv)" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2

    - name: Convert to JSON
      uses: ./.github/actions/convert-markdown-to-json
      env:
        ARM_ACCESS_TOKEN: ${{ steps.get-arm-token.outputs.token }}
        MSGRAPH_ACCESS_TOKEN: ${{ steps.get-msgraph-token.outputs.token }}
      with:
        user_email: 'azure-tiering-integration-robot@gmail.com'
        user_name: 'azure-tiering-integration-robot'
