name: Detect untiered assets

on:
  workflow_dispatch: {}
  schedule:
    - cron: "00 01 * * *"  # Every day at 1:00 AM UTC

permissions:
  contents: write
  id-token: write

jobs:
  detect_untiered_assets:
    runs-on: ubuntu-latest
    steps:
    - name: Az Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302   # v2.2.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Get MS Graph access token
      id: get-token
      run: echo "token=$(az account get-access-token --resource=https://graph.microsoft.com --query accessToken -o tsv)" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2

    - name: Run AzTierWatcher
      uses: ./.github/actions/detect-untiered
      env:
        MSGRAPH_ACCESS_TOKEN: ${{ steps.get-token.outputs.token }}
      with:
        user_email: 'azure-tiering-robot@gmail.com'
        user_name: 'azure-tiering-robot'
